ACTIVE_GENERATION_RUN_STATUSES = {"active", "streaming"}
TERMINAL_GENERATION_RUN_STATUSES = {"completed", "failed", "cancelled", "interrupted"}
TERMINAL_GENERATION_RUN_EVENT_TYPES = {"run_completed", "run_failed", "run_cancelled"}
DEFAULT_GENERATION_RUN_STALE_AFTER_SECONDS = 30
DEFAULT_GENERATION_RUN_EVENT_REPLAY_LIMIT = 100
DEFAULT_GENERATION_RUN_EVENT_RETENTION_DAYS = 14
DEFAULT_GENERATION_RUN_EVENT_PRUNE_BATCH_SIZE = 200
