from datetime import UTC, datetime, timedelta

from sqlalchemy import delete, func, select
from sqlalchemy.orm import Session, selectinload

from app.db.models import ConversationThread, DraftVariant, GenerationRun, GenerationRunEvent, Turn, WorkspaceSession
from app.schemas.domain import (
    ConversationThreadCreate,
    ConversationThreadSnapshot,
    DomainHistoryItem,
    DraftVariantCreate,
    DraftVariantStateUpdate,
    GenerationRunClaim,
    GenerationRunHeartbeat,
    GenerationRunLiveFeedAttachment,
    GenerationRunProgressEvent,
    GenerationRunProgressSnapshot,
    GenerationRunReconcileRequest,
    GenerationRunStatusUpdate,
    RecoverableRunProjection,
    SourceSnapshot,
    TurnCreate,
    TurnStatusUpdate,
    WorkspaceSessionSnapshot,
    WorkspaceSessionUpsert,
)
from app.services.diagnostics_service import record_generation_run_maintenance_outcome
from app.services.domain.constants import (
    ACTIVE_GENERATION_RUN_STATUSES,
    DEFAULT_GENERATION_RUN_EVENT_PRUNE_BATCH_SIZE,
    DEFAULT_GENERATION_RUN_EVENT_REPLAY_LIMIT,
    DEFAULT_GENERATION_RUN_EVENT_RETENTION_DAYS,
    DEFAULT_GENERATION_RUN_STALE_AFTER_SECONDS,
    TERMINAL_GENERATION_RUN_EVENT_TYPES,
    TERMINAL_GENERATION_RUN_STATUSES,
)
from app.services.domain.errors import GenerationRunConflictError
from app.services.domain.generation_events import (
    append_generation_run_event,
    find_existing_generation_run_event,
    generation_run_event_to_progress_event,
    list_generation_run_events,
    prune_generation_run_events,
    prune_terminal_generation_run_events,
    record_generation_run_terminal_event,
)
from app.services.domain.generation_lifecycle import (
    apply_generation_run_lifecycle,
    as_utc,
    event_type_for_generation_run_terminal_status,
    is_generation_run_stale,
    sequence_for_generation_run_status,
    timestamp_for_generation_run_status,
)
from app.services.domain.generation_progress import (
    build_generation_run_progress_events,
    build_replay_only_live_feed_attachment,
    get_generation_run_progress_snapshot,
)
from app.services.domain.generation_runs import (
    claim_generation_run,
    heartbeat_generation_run,
    is_generation_run_active,
    list_active_generation_runs,
    reconcile_stale_generation_runs,
    reconcile_turn_for_generation_run,
    reconcile_workspace_routing_for_generation_run,
    update_generation_run_status,
)
from app.services.domain.sessions import apply_compose_target, ensure_workspace_session_exists, upsert_workspace_session
from app.services.domain.snapshots import (
    build_latest_recoverable_run_projection,
    get_session_snapshot,
    get_thread_snapshot,
    latest_generation_run_activity,
    latest_generation_run_event_at,
    latest_thread_activity,
    list_recent_domain_history,
    list_threads_paginated,
)
from app.services.domain.threads import create_or_update_thread
from app.services.domain.turns import apply_turn_lifecycle, create_or_update_turn, update_turn_lifecycle, update_turn_status
from app.services.domain.variants import create_or_update_variant, update_variant_state, variants_for_thread, variants_for_turn

__all__ = [
    "ACTIVE_GENERATION_RUN_STATUSES",
    "ConversationThread",
    "ConversationThreadCreate",
    "ConversationThreadSnapshot",
    "DEFAULT_GENERATION_RUN_EVENT_PRUNE_BATCH_SIZE",
    "DEFAULT_GENERATION_RUN_EVENT_REPLAY_LIMIT",
    "DEFAULT_GENERATION_RUN_EVENT_RETENTION_DAYS",
    "DEFAULT_GENERATION_RUN_STALE_AFTER_SECONDS",
    "DomainHistoryItem",
    "DraftVariant",
    "DraftVariantCreate",
    "DraftVariantStateUpdate",
    "GenerationRun",
    "GenerationRunClaim",
    "GenerationRunConflictError",
    "GenerationRunEvent",
    "GenerationRunHeartbeat",
    "GenerationRunLiveFeedAttachment",
    "GenerationRunProgressEvent",
    "GenerationRunProgressSnapshot",
    "GenerationRunReconcileRequest",
    "GenerationRunStatusUpdate",
    "RecoverableRunProjection",
    "Session",
    "SourceSnapshot",
    "TERMINAL_GENERATION_RUN_EVENT_TYPES",
    "TERMINAL_GENERATION_RUN_STATUSES",
    "Turn",
    "TurnCreate",
    "TurnStatusUpdate",
    "UTC",
    "WorkspaceSession",
    "WorkspaceSessionSnapshot",
    "WorkspaceSessionUpsert",
    "append_generation_run_event",
    "apply_compose_target",
    "apply_generation_run_lifecycle",
    "apply_turn_lifecycle",
    "as_utc",
    "build_generation_run_progress_events",
    "build_latest_recoverable_run_projection",
    "build_replay_only_live_feed_attachment",
    "claim_generation_run",
    "create_or_update_thread",
    "create_or_update_turn",
    "create_or_update_variant",
    "datetime",
    "delete",
    "ensure_workspace_session_exists",
    "event_type_for_generation_run_terminal_status",
    "find_existing_generation_run_event",
    "func",
    "generation_run_event_to_progress_event",
    "get_generation_run_progress_snapshot",
    "get_session_snapshot",
    "get_thread_snapshot",
    "heartbeat_generation_run",
    "is_generation_run_active",
    "is_generation_run_stale",
    "latest_generation_run_activity",
    "latest_generation_run_event_at",
    "latest_thread_activity",
    "list_active_generation_runs",
    "list_generation_run_events",
    "list_recent_domain_history",
    "list_threads_paginated",
    "prune_generation_run_events",
    "prune_terminal_generation_run_events",
    "reconcile_stale_generation_runs",
    "reconcile_turn_for_generation_run",
    "reconcile_workspace_routing_for_generation_run",
    "record_generation_run_maintenance_outcome",
    "record_generation_run_terminal_event",
    "select",
    "selectinload",
    "sequence_for_generation_run_status",
    "timedelta",
    "timestamp_for_generation_run_status",
    "update_generation_run_status",
    "update_turn_lifecycle",
    "update_turn_status",
    "update_variant_state",
    "upsert_workspace_session",
    "variants_for_thread",
    "variants_for_turn",
]
